### ISSUE TITLE
the example is error

### ISSUE THREAD

**Issue by lywaterman** [torch/tds#8] opened 2016-01-15 06:20 UTC
tds = require 'tds'
require 'torch'

-- create a vector containing heterogeneous data
d = tds.Vec(4, 5, torch.rand(3), nil, "hello world")

-- serialize in a buffer
f = torch.MemoryFile("rw")
f:writeObject(d)

-- unserialize
f:seek(1)
print(f:readObject())

this will break when i run it with luajit 2.1 beta1, but if i remove the nil in the Vec, this will be ok

**Comment by soumith** [comment] 2016-01-15 06:23
I just tested this on OSX with LuaJIT 2.1.0-beta1 and it seems to work fine. 
What OS did you test this on?

**Comment by deltheil** [comment] 2016-01-15 08:47
I do reproduce the problem (on Linux):

```
tds/vec.lua:118: lua table with number keys (1...N) expected
```

@soumith it looks like it's a *regression* that has been introduced at commit 65cce40, i.e. the [is-a-sequence detection](https://github.com/torch/tds/blob/100f2054a3299bf22fe38c086a3a4de473a2fd0a/vec.lua#L106-L112) introduced does not work when the list of input args has a hole (a `nil` element somewhere). Prior to this commit the [iteration over input args](https://github.com/torch/tds/blob/e5055ec407d25cab165723e5099344d24236364e/vec.lua#L55-L60) did the job.

So either we fix the example in the README or find a way to support again this kind of construct. What do you think?

**Comment by lywaterman** [comment] 2016-01-16 05:34
i test it on ubuntu 12.04

**Comment by soumith** [comment] 2016-02-02 20:54
fixed now in master. thanks to Ronan.

**Closed by soumith** 2016-02-02 20:54 UTC
